package it.redhat.hacep.playground.rules.reward.catalog;

import it.redhat.hacep.playground.rules.model.BroFact;
import it.redhat.hacep.playground.rules.model.SuricataFact;

declare BroFact
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 10m )
end

declare SuricataFact
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 10m )
end

rule "Flag more than four DNS responses from the same host in the last 5 minutes"
when
        $bro : BroFact( _at_stream == "dns", $host: id_resp_h) over window:length(1)
	$numberOfTimes : Number( intValue > 4 ) from accumulate (
	    	$dnsRespCount : BroFact( _at_stream == $bro._at_stream, id_resp_h == $host) over window:time(5m),
		count($dnsRespCount))
then
	System.err.println("Rule 0: DNS response from " + $host + " occurred " + $numberOfTimes + " in last five minutes");
end

rule "BroFact test rule 1"
when
	$bro : BroFact() over window:length(1)
then
	System.err.println("Rule 1: BroFact found " + $bro);
end

rule "BroFact test rule 2"
when
	$bro : BroFact( _at_stream == "dns" ) over window:length(1)
then
	System.err.println("Rule 2: BroFact found " + $bro);
end

